// <auto-generated />
namespace SimpleBlog_EF.DataAccessLayer.AppUserMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AppUserInitialCreateandSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppUserInitialCreateandSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201702140910562_AppUser Initial Create and Seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
